### ISSUE TITLE
Create an MVP

### ISSUE THREAD

**Issue by TabrisArg** [2B-Games/Lost-Conscience#4]
- [x] Create Hospital room #5 
- [x] Create Transportation mechanic #6 
- [x] Create destination rooms #7
